### ISSUE TITLE
Make this addon inert on Ember versions with native support for the feature

### ISSUE THREAD

**Issue by chancancode** [NullVoxPopuli/ember-functions-as-helper-polyfill#121]
Once this feature is [enabled](https://github.com/emberjs/ember.js/issues/20054) on the Ember side, this addon should be updated to be completely inert (i.e. have no effect in the consuming app's build output). There is a recent example of that [here](https://github.com/ember-polyfills/ember-named-blocks-polyfill/blob/main/index.js). I'm not sure if there is a better way to do it that is more Embroider-friendly, but at the end of the day, I am not sure it really matters. If the reason this is using v1 build hooks is to disable itself on modern version of Ember anyway, it seems ok? cc @ef4

**Comment by ef4** [comment]
Yes, the example you linked should be embroider-compatible, and since this package is a v1 addon it's a good pattern for it to use.

**Comment by NullVoxPopuli** [comment]
excellent, I can get the auto-removal stuff setup today
